---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ical-proxy-helm.fullname" . }}-config
  labels:
    {{- include "ical-proxy-helm.labels" . | nindent 4 }}
data:
  config.yml: |
    http:
      host: ''
      port: {{ .Values.service.port }}

    calendars: {{ index .Values "ical-proxy" "calendars" | toYaml | nindent 6 }}
